modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Trinsdar/Terrestria-Reforged/issues"

[[mods]]
modId="terrestria"
version="${version}"
displayName="Terrestria Reforged"
displayURL="https://github.com/Trinsdar/Terrestria-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, coderbot16, NeusFear, TerraformersMC"
description='''A mod enhancing the detail of Minecraft with unique and vibrant biomes. Inspired by ExtrabiomesXL.'''
[[dependencies.terrestria]]
modId="forge"
mandatory=true
versionRange="[40.2.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.terrestria]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.terrestria]]
modId="terrablender"
mandatory=true
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"
