modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Trinsdar/Terrestria-Reforged/issues"

[[mods]]
modId="terrestria_client"
version="${version}"
displayName="Terrestria Reforged: Client"
displayURL="https://github.com/Trinsdar/Terrestria-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, coderbot16, NeusFear, TerraformersMC"
description='''A mod enhancing the detail of Minecraft with unique and vibrant biomes. Inspired by ExtrabiomesXL.'''
[[dependencies.terrestria_client]]
modId="forge"
mandatory=true
versionRange="[40.1.73,)"
ordering="AFTER"
side="BOTH"
[[dependencies.terrestria_client]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"
