modLoader="javafml"
license="LGPLv3"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Trinsdar/Terrestria-Reforged/issues"

[[mods]]
modId="terrestria_common"
version="${version}"
displayName="Terrestria Reforged: Common"
displayURL="https://github.com/Trinsdar/Terrestria-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''A mod enhancing the detail of Minecraft with unique and vibrant biomes. Inspired by ExtrabiomesXL.'''
[[dependencies.terrestria_common]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.terrestria_common]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="AFTER"
side="BOTH"
